var Scoreflex=function(G,H,I){var y;y={inArray:function(l,q){for(var g=0;g<q.length;g++)if(q[g]===l)return!0;return!1},rawurlencode:function(l){l=(l+"").toString();return encodeURIComponent(l).replace(/!/g,"%21").replace(/'/g,"%27").replace(/\(/g,"%28").replace(/\)/g,"%29").replace(/\*/g,"%2A")},getUUID:function(){var l=Array(31);if(window.crypto&&crypto.getRandomValues){var q=new Uint8Array(31);crypto.getRandomValues(q);for(var g=0;31>g;g++)l[g]=q[g]&15}else for(g=0;31>g;g++)l[g]=16*Math.random()|
0;var r=0;return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(g){var q=l[r++];return("x"==g?q:q&3|8).toString(16)})},getDeviceId:function(){var l;window.localStorage&&(l=localStorage.getItem("deviceId"));l||(l=this.getUUID()+"-"+(+new Date).toString(16),window.localStorage&&localStorage.setItem("deviceId",l));return l},fireEvent:function(l,q,g){var r;if(document.createEventObject)return r=document.createEventObject(),r.data=g,l.fireEvent("on"+q,r);r=document.createEvent("HTMLEvents");
r.initEvent(q,!0,!0);r.data=g;return!l.dispatchEvent(r)}};return function(l,q,g){var r="af ar be bg bn ca cs da de el en en_GB en_US es es_ES es_MX et fa fi fr fr_FR fr_CA he hi hr hu id is it ja ko lt lv mk ms nb nl pa pl pt pt_PT pt_BR ro ru sk sl sq sr sv sw ta th tl tr uk vi zh zh_CN zh_TW zh_HK".split(" "),p=!1,C=null,M=null,J=!0,K=function(){var a=function(a,b){var d=new XMLHttpRequest;"withCredentials"in d?d.open(a,b,!0):"undefined"!=typeof XDomainRequest?(d=new XDomainRequest,d.open(a,b)):
d=null;return d},c=function(a,b){return a.k==b.k?a.v<b.v?-1:1:a.k<b.k?-1:1};return{request:function(e,b,d,c,k,f){var t=a(e,b);if(void 0!==k)for(var u in k)t.setRequestHeader(u,k[u]);if(t){if(f)for(u=["onerror","ontimeout","onabort","onloadend"],b=0;b<u.length;b++)f[u[b]]&&(t[u[b]]=f[u[b]]);t.onload=function(){if(f){try{var a;a:{try{a=JSON.parse(this.responseText);break a}catch(b){}a=null}t.responseJSON=a}catch(d){}200==this.status&&f.onload?f.onload.apply(this,arguments):f.onerror&&f.onerror.apply(this,
arguments)}};"POST"===e?t.send(d):t.send()}},getSignature:function(a,b,d,h){void 0===h&&(h="");void 0===d&&(d=[]);var k,f=document.createElement("a");f.href=b;b=f.protocol.substr(0,f.protocol.length-1).toLowerCase();var t=f.hostname.toLowerCase(),u=f.pathname,f=f.search;0<f.length&&"?"===f[0]&&(f=f.substr(1));var f=f.split("&"),z=[],l;for(k=0;k<f.length;k++)""!==f[k]&&(l=f[k].split("=",2),z.push({k:l[0],v:l[1]}));var f=y.rawurlencode,n;for(n in d)z.push({k:f(n),v:f(d[n])});z.sort(c);d=[];for(k=0;k<
z.length;k++)d.push(z[k].k+"="+z[k].v);d=d.join("&");a=a+"&"+f(b+"://"+t+u)+"&"+f(d)+"&"+f(h);a=CryptoJS.HmacSHA1(a,M).toString(CryptoJS.enc.Base64);return'Scoreflex sig="'+f(a)+'", meth="0"'}}}(),x={ScoreflexSessionEvent:function(a,c){return{name:"session",login:a,logout:c}},ScoreflexPlayEvent:function(a){return{name:"play",leaderboard:a}},ScoreflexChallengeEvent:function(a){return{name:"challenge",challenge:a}},fire:function(a){y.fireEvent(window,"ScoreflexEvent",a)}},v=function(){var a=function(a){return(J?
"https://sandbox.api.scoreflex.com":"https://api.scoreflex.com")+"/v1"+a},c=function(a){void 0===a&&(a={});var d=A()||{},c=d.lang||window.navigator.language;a.lang=y.inArray(c,r)?c:"en";d.accessToken&&(a.accessToken=d.accessToken);return a},e=function(a){var d=[],c;for(c in a)d.push(encodeURIComponent(c)+"="+encodeURIComponent(a[c]));return d.join("&")};return{post:function(b,d,h,k){d=c(d);b=a(b);var f=e(d);d={"Content-type":"application/x-www-form-urlencoded","X-Scoreflex-Authorization":K.getSignature("POST",
b,d,h)};K.request("POST",b,f,h,d,k)},get:function(b,d,h){d=c(d);b=a(b);(d=e(d))&&(b=b+"?"+d);K.request("GET",b,{},void 0,{},h)}}}(),w=function(){var a={},c={},e=[],b=function(b){if(!a[b]){var d=document.createElement("iframe");d.id="scoreflexWebClient_"+b;a[b]=d;d.onload=function(){c[b]=d.contentWindow}}return a[b]},d=function(a){for(var b=0;b<e.length;b++)if(e[b]===a){e.splice(b,1);break}},h=null;window.addEventListener("message",function(a){if("https://api.scoreflex.com"==a.origin||"https://sandbox.api.scoreflex.com"==
a.origin){var b=a.data;if(b!==h){h=b;var d=document.createElement("a");d.href=b;if("/v1/web/callback"==d.pathname){b=d.search;0<b.length&&"?"==b[0]&&(b=b.substr(1));var d=b.split("&"),b={},e,n,m;for(n=0;n<d.length;n++)d[n]&&(e=d[n].split("=",2),b[e[0]]=e[1]);d=null;for(m in c)if(a.source===c[m]){d=m;break}a=d;d=b.code;m=b.data?JSON.parse(decodeURIComponent(b.data)):{};switch(d){case "200000":f(a);D(null,!0);N();break;case "200001":f(a);break;case "200002":x.fire(x.ScoreflexPlayEvent(O.get(m.leaderboardId)));
f(a);break;case "200003":f(a);p&&(a=A(),!0===a.anonymous&&(m={clientId:C,devicePlatform:"Web",deviceModel:window.navigator.userAgent||"browser",deviceId:y.getDeviceId(),state:P(!0)},a.accessToken&&(m.anonymousAccessToken=a.accessToken,m.forceMerge="true"),m=s(m,void 0),w.show("/oauth/web/authorize",m,void 0,{style:"full",noSid:!0})));break;case "200004":b=m.code;m=m.state;f(a);R({code:b,state:m});break;case "200005":b=m.url;m=m.mode;f(a);k(b,{},{style:m});break;case "200006":f(a);break;case "200007":b=
m.challengeInstanceId;m=m.challengeConfigId;f(a);x.fire(x.ScoreflexChallengeEvent(Q.get(b,m)));break;case "200008":f(a);break;case "200009":f(a);break;case "200010":f(a)}}}}},!1);var k=function(a,c,h,k){h=h||{};if(void 0!==k)for(var n in k)void 0===h[n]&&(h[n]=k[n]);k=c;if(-1!==a.indexOf("://"))c=a;else if(c=J,A().sid){n=h;void 0===k&&(k={});void 0===n&&(n={});var m=A()||{},l=m.lang||window.navigator.language;k.lang=y.inArray(l,r)?l:"en";m.sid&&!n.noSid&&(k.sid=m.sid);n=[];for(var g in k)n.push(encodeURIComponent(g)+
"="+encodeURIComponent(k[g]));g=n.join("&");c=(c?"https://sandbox.api.scoreflex.com":"https://api.scoreflex.com")+"/v1"+a+"?"+g}else c=null;c?(a=h.id||h.style||"full",g=b(a),g.src=c+"#start",h="scoreflexWebClient_"+h.style,void 0!==h&&(c=g.getAttribute("data-stylename"),c!==h&&(g.classList.remove(c),g.classList.add(h),g.setAttribute("data-stylename",h))),document.body.appendChild(g),d(a),e.push(a)):f()},f=function(a){var c;a||(a=0<e.length?e[e.length-1]:null);a&&(c=b(a))&&c.parentNode&&(c.parentNode.removeChild(c),
d(a))};return{show:k,close:f}}(),E=function(){_ns="SFX_"+l+"_"+(g?"1":"0");return{get:function(a){return(a=localStorage.getItem(_ns+a))?JSON.parse(a):null},set:function(a,c){var e=JSON.stringify(c);return localStorage.setItem(_ns+a,e)},rm:function(a){return localStorage.removeItem(_ns+a)}}}(),B=function(a,c){var e=function(){return c||{}};return{getId:function(){return a},getData:e,getNickname:function(){return e().nickName||""},showProfile:function(b,d){F.showProfile(a,b,d)},showFriends:function(b,
d){showPlayerFriends(a,b,d)}}},F=function(){var a={};return{get:function(c,e,b,d){if(p)if(void 0===b&&(b={}),!d&&a[c]){if(b.onload){var h=B(c,a[c]);setTimeout(function(){b.onload.call(null,h)},0)}}else{var k=b.onload;b.onload=function(){var b=this.responseJSON||{};a[c]=b;b=B(c,b);k.call(this,b)};v.get("/players/"+c,e,b)}},getCurrent:function(){var a=(A()||{}).me||{};return B(a.id,a)},showProfile:function(a,e,b){p&&(void 0===a&&(a="me"),e=s({},e),w.show("/web/players/"+a,e,b,{style:"full"}))},showFriends:function(a,
e,b){p&&(void 0===a&&(a="me"),e=s({},e),w.show("/web/players/"+a+"/friends",e,b,{style:"full"}))}}}(),G=function(a){var c=function(b,d,c){p&&(b={score:b},b=s(b,d),v.post("/scores/"+a,b,void 0,c))},e=function(b,d){if(p){var c=s({},b);w.show("/web/scores/"+a+"/ranks",c,d,{style:"panel"})}};return{getId:function(){return a},submitScore:c,show:function(b,d){if(p){var c=s({},b);w.show("/web/leaderboards/"+a,c,d,{style:"full"})}},showOverview:function(b,d){if(p){var c=s({},b);w.show("/web/leaderboards/"+
a+"/overview",c,d,{style:"full"})}},showRankbox:e,submitScoreAndShowRankbox:function(a,d,h){c(a,d);d=d||{};d.score=a;e(d,h)}}},O=function(){return{get:function(a){return G(a)}}}(),H=function(a,c){var e=null,b=function(b,d){if(p){var c=s(c,b);v.get("/challenges/instances/"+a,c,d)}},d=function(c,e,f){if(p)if(c&&void 0!==c.turnSequence){var g={body:JSON.stringify(c)},g=s(g,e);v.post("/challenges/instances/"+a+"/turns",g,void 0,f)}else b({fields:"turn"},{onload:function(){var a=c||{};a.turnSequence=((this.responseJSON||
{}).turn||{}).sequence||0;d(a,e,f)},onerror:(f||{}).onerror})};return{getInstanceId:function(){return a},getConfigId:function(){return c},getDetails:b,getPlayers:function(a,c,d){void 0===c&&(c={});d||null===cache_participants?b(a,{onload:function(){var a=(this.responseJSON||{}).participants||{},b={},d=0,f=0,h;for(h in a)d++,b[h]=B(h,{});var g=function(a){f++;a.id&&(b[a.id]=B(a.id,a));f>=d&&(e=b,setTimeout(function(){c.onload.call(null,b)},0))};for(h in a)F.get(h,{},{onload:function(){g(this.responseJSON||
{})}})},onerror:function(){c.onerror&&handler.onerror.apply(this,arguments)}}):c.onload&&setTimeout(function(){c.onload.call(null,e)},0)},getTurns:function(b,c){if(p){var d=s(d,b);v.get("/challenges/instances/"+a+"/turns",d,c)}},submitTurn:d,submitTurnScore:function(a,b,c){d({score:a},b,c)},showDetails:function(b,c){if(p){var d=s({},b);w.show("/web/challenges/instances/"+a,d,c,{style:"full"})}}}},Q=function(){return{showChallenges:function(a,c){if(p){var e=s({},a);w.show("/web/challenges",e,c,{style:"full"})}},
get:function(a,c){return H(a,c)}}}(),A=function(){var a=E.get("sessions");a||(a={});return a.player?a.player:a.anonymous},D=function(a,c){var e=E.get("sessions");e||(e={});!0===c?e.player=a:e.anonymous=a;E.set("sessions",e)},L=null,P=function(a){if(!0===a||null===L)L="S"+ +new Date;return L},s=function(a,c){void 0===a&&(a={});if(void 0!==c)for(var e in c)a[e]=c[e];return a},I=function(a){var c={clientId:C,devicePlatform:"Web",deviceModel:window.navigator.userAgent||"browser",deviceId:y.getDeviceId()};
v.post("/oauth/anonymousAccessToken",c,void 0,a)},N=function(){var a=A(),c={onload:function(){var a=this.responseJSON||{},b=(a.accessToken||{}).token||null,c=a.sid||null,a=a.me||{},h=a.id||null,g=a.language||null;b&&c&&h&&D({anonymous:!0,accessToken:b,sid:c,playerId:h,lang:g,me:a},!1);p=!0;x.fire(x.ScoreflexSessionEvent(!1,!0))},onerror:function(){}};a&&a.accessToken&&a.sid&&a.playerId?c.onload&&setTimeout(c.onload,0):I(c)},R=function(a){a.state===P()&&(a={code:a.code,clientId:C},handlers={onload:function(){var a=
this.responseJSON||{},e=(a.accessToken||{}).token||null,b=a.sid||null,a=a.me||{},d=a.id||null,g=a.language||null;e&&b&&d&&(D({anonymous:!1,accessToken:e,sid:b,playerId:d,lang:g,me:a},!0),D(null,!1));F.showProfile();x.fire(x.ScoreflexSessionEvent(!0,!1))},onerror:function(){}},v.post("/oauth/accessToken",a,void 0,handlers))};(function(a,c,e){p||(C=a,M=c,J=e,N())})(l,q,g);return{reset:function(){E.rm("sessions")},RestClient:v,ping:function(a){v.get("/network/ping",{},a)},WebClient:w,Leaderboards:O,
Players:F,Challenges:Q}}(G,H,I)};
